# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c228508b895a01cf340de5f6a104fdab8dcb91fd87a4361e5bcfae6bb4561101d6af4ae5776e4b87ff41fe5026fe86f67e5a9fa1654d628087589219f01e0e7f

test:
  secret_key_base: ade53249047f849e86b73e014b43090299441d1435abafa509ab6f67013dd01bb457f0e4978908090f6bc4c07281af572f007b52d2ed865d119ce264641d7c51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
